version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      -db

  queue:
    build: 
      context:
      dockerfile: Dockerfile
      command: 'python concumer.py'
      depends_on:
       -db

  db:
    image: mariadb
    restart: always
    enviroment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSORD: PASSWORD
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
       -"3306"