# Generated by Django 3.2.12 on 2023-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borrower_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerfeeditem',
            name='registery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
