# Generated by Django 3.2.12 on 2023-10-28 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(choices=[('William Shakespeare', 'william shakespeare'), ('Agatha Christie', 'agatha christie'), ('Barbara Cartland', 'barbara cartland'), ('George Orwell', 'george orwell')], default='shakespeare', max_length=255)),
                ('author_city', models.CharField(choices=[('QOM', 'qom'), ('TEHRAN', 'tehran'), ('MASHHAD', 'mashhad')], default='Qom', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('science fiction', 'Science fiction'), ('fiction', 'Fiction'), ('horror', 'Horror')], default='Genre', max_length=50)),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('isbn', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('authors', models.ManyToManyField(related_name='books', to='book.Author')),
            ],
        ),
    ]
