# Generated by Django 3.2.12 on 2023-10-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(choices=[('1', 'william shakespeare'), ('2', 'agatha christie'), ('3', 'barbara cartland'), ('4', 'george orwell')], default='shakespeare', max_length=255),
        ),
    ]
