# Generated by Django 3.2.12 on 2023-11-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(choices=[('william shakespeare', 'william shakespeare'), ('agatha christie', 'agatha christie'), ('barbara cartland', 'barbara cartland'), ('george orwell', 'george orwell')], default='shakespeare', max_length=255),
        ),
    ]
